import csv
import os
from docarray import dataclass
from docarray import Document, DocumentArray
from docarray.typing import Image, Text


@dataclass
class Artwork:
    image: Image
    title: Text
    description: Text


image_folder = '../raw_data/aws10k_sm'


def convert_to_docarray(filename):
    existing_images = os.listdir(image_folder)

    artworks = DocumentArray()

    with open(filename) as csvfile:
        csv_reader = csv.DictReader(csvfile, delimiter=',')
        for row in csv_reader:
            image_file = f'{row["documents_0_metadata_accession_no"]}.jpg'
            if image_file in existing_images:
                artwork = Artwork(
                    image=f'{image_folder}/{image_file}',
                    title=row['documents_0_title'],
                    description=row['documents_0_content'],
                )
                doc = Document(artwork)
                artworks.append(doc)

    artworks.save_binary('artworks_all.docarray')
    artworks[:20].save_binary('artworks_small.docarray')


def push_all():
    da = DocumentArray.load_binary(f'artworks_all.docarray')
    da.push(name='artworks_all')


convert_to_docarray('../raw_data/csv/data_csv_df_10K_nhb_all.csv')
push_all()
'''
{
    '': '0',
    'documents_0_id': '47E60712-DB30-42AE-BFDF-3C4918065A91',
    'documents_0_title': 'Handbill for the Cantonese movie, ‘Peach Blossom Crossing’',
    'documents_0_source': 'roots_collections',
    'documents_0_path': 'https://www.roots.gov.sg/Collection-Landing/listing/1142557',
    'documents_0_content': 'This handbill was used to advertise the Cantonese movie, ‘Peach Blossom Crossing’ (桃花搭渡, Taohuadadu). During its Singapore run, the movie was screened at the Oriental (东方, Dongfang) and Grand (大光, Daguang) cinemas.Between the 1950s and 1960s, most Mandarin, Cantonese and other Chinese-dialect movies were made in Hong Kong by film production companies with financial support from Singapore-based film studios such as Shaw Brothers, Cathay and Kong Ngee (光艺, Guanyi). These studios were also involved in the distribution and exhibition of these movies in Singapore and the rest of Southeast Asia through their network of cinemas. In the early 1970s, Mandarin movies from Taiwan became popular, but by the late 1970s, Hong Kong movies were dominant once more.',
    'documents_0_lastModifiedDate': '04/08/2021',
    'documents_0_metadata_rootsUuid': '47e60712db3042aebfdf3c4918065a91',
    'documents_0_metadata_date_period': '1958',
    'documents_0_metadata_collection_of': 'National Museum of Singapore',
    'documents_0_metadata_material_0': 'Paper',
    'documents_0_metadata_image_url': 'https://www.roots.gov.sg/CollectionImages/1142557.jpg',
    'documents_0_metadata_accession_no': '2007-00335',
    'documents_0_metadata_nlb_type': 'Document',
    'documents_0_metadata_categories_0': '',
    'documents_0_metadata_region': 'Singapore',
    'documents_0_metadata_pageId': '1142557',
    'documents_0_metadata_dimension': 'Object size: 19.5 x 27.2 cm',
    'documents_0_docFormat': 'html',
    'documents_0_highlight': '',
    'documents_0_tags': '{}',
    'id': '1950385757',
    'total': '1835',
    'size': '1',
    'documents_0_metadata_creator': '',
    'documents_0_tags_country_0': '',
    'documents_0_tags_material_0': '',
    'documents_0_tags_city_0': '',
    'documents_0_tags_subject_0': '',
    'documents_0_tags_subject_1': '',
    'documents_0_tags_subject_2': '',
    'documents_0_tags_subject_3': '',
    'documents_0_tags_subject_4': '',
    'documents_0_tags_subject_5': '',
    'documents_0_tags_subject_6': '',
    'documents_0_tags_subject_7': '',
    'documents_0_tags_subject_8': '',
    'documents_0_tags_subject_9': '',
    'documents_0_tags_subject_10': '',
    'documents_0_tags_subject_11': '',
    'documents_0_tags_subject_12': '',
    'documents_0_tags_subject_13': '',
    'documents_0_tags_person_0': '',
    'documents_0_tags_topic_0': '',
    'documents_0_tags_topic_1': '',
    'documents_0_tags_topic_2': '',
    'documents_0_tags_topic_3': '',
    'documents_0_tags_topic_4': '',
    'documents_0_tags_topic_5': '',
    'documents_0_tags_topic_6': '',
    'documents_0_tags_organisation_0': '',
    'documents_0_tags_collection_0': '',
    'documents_0_tags_material_1': '',
    'documents_0_tags_organisation_1': '',
    'documents_0_tags_organisation_2': '',
    'documents_0_tags_topic_7': '',
    'documents_0_tags_singheritage_0': '',
    'documents_0_metadata_credit_line': '',
    'documents_0_tags_geographics_0': '',
    'documents_0_tags_topic_8': '',
    'documents_0_tags_color_0': '',
    'documents_0_tags_color_1': '',
    'documents_0_tags_awards_0': '',
    'documents_0_tags_topic_9': '',
    'documents_0_tags_singheritage_1': '',
    'documents_0_metadata_technique_0': '',
    'documents_0_metadata_materials_name': '',
    'documents_0_metadata_creation_place_original_location': '',
    'documents_0_metadata_subject_terms_3': '',
    'documents_0_metadata_subject_terms_1': '',
    'documents_0_metadata_subject_terms_2': '',
    'documents_0_metadata_accession_no_csv': '',
    'documents_0_metadata_techniques_name': '',
    'documents_0_metadata_shape': '',
    'documents_0_metadata_object_colour': '',
    'documents_0_metadata_preference': '',
    'documents_0_metadata_sgcool_label_text': '',
    'documents_0_metadata_edition_description': '',
    'documents_0_metadata_creation_date': '',
    'documents_0_metadata_creator_role': '',
    'documents_0_metadata_creator_2': '',
    'documents_0_metadata_creator_1': '',
    'documents_0_metadata_object_work_type': '',
    'documents_0_metadata_styles_periods_indexing_terms': '',
    'documents_0_metadata_title_text': '',
    'documents_0_metadata_physical_appearance': '',
    'documents_0_tags_technique_0': '',
    'documents_0_tags_objecttype_0': '',
    'documents_0_tags_objecttype_1': '',
    'documents_0_tags_material_2': '',
    'documents_0_tags_subject_14': '',
    'documents_0_tags_subject_15': '',
    'documents_0_tags_subject_16': '',
    'documents_0_metadata_material_1': '',
    'documents_0_tags_material_3': '',
    'documents_0_tags_material_4': '',
    'documents_0_tags_subject_17': '',
    'documents_0_tags_singheritage_2': '',
    'documents_0_tags_singheritage_3': '',
    'documents_0_tags_geobuildings_0': '',
    'documents_0_tags_geobuildings_1': '',
    'documents_0_tags_person_1': '',
    'documents_0_metadata_object_type_0': '',
    'documents_0_tags_country_1': '',
    'documents_0_tags_objecttypetaxonomytopic_0': '',
    'documents_0_tags_events_0': '',
    'documents_0_tags_color_2': '',
    'documents_0_metadata_end_date': '',
    'documents_0_metadata_object_type': '',
    'documents_0_metadata_content': '',
    'documents_0_metadata_start_date': '',
    'documents_0_tags_geographics_1': '',
    'documents_0_tags_geographics_2': '',
    'documents_0_metadata_collection_of_0': '',
    'documents_0_metadata_year_period_0': '',
    'documents_0_metadata_accession_no_0': '',
    'documents_0_metadata_nlb_type_0': '',
    'documents_0_metadata_region_0': '',
    'documents_0_metadata_region_1': '',
    'documents_0_metadata_dimension_0': '',
    'documents_0_tags_shape_0': '',
    'documents_0_tags_language_0': '',
    'documents_0_metadata_creator_0': '',
    'documents_0_metadata_technique_1': '',
    'documents_0_metadata_material_2': '',
    'documents_0_metadata_categories_1': '',
    'documents_0_metadata_subject_terms': '',
    'documents_0_metadata_object_type_1': '',
    'documents_0_tags_technique_1': '',
    'documents_0_tags_topic_10': '',
    'documents_0_tags_objecttype_2': '',
    'documents_0_tags_objecttype_3': '',
    'documents_0_metadata_inscriptions': '',
    'documents_0_tags_color_3': '',
    'documents_0_metadata_context': '',
    'documents_0_tags_city_1': '',
    'documents_0_tags_technique_2': '',
    'documents_0_metadata_region_2': '',
    'documents_0_metadata_title_language': '',
    'documents_0_tags_city_2': '',
    'documents_0_tags_objecttypetaxonomytopic_1': '',
    'documents_0_tags_topic_11': '',
    'documents_0_tags_shape_1': '',
    'documents_0_tags_country_2': '',
    'documents_0_tags_country_3': '',
    'documents_0_metadata_material_3': '',
    'documents_0_metadata_material_4': '',
    'documents_0_tags_subject_18': '',
    'documents_0_tags_subject_19': '',
    'documents_0_tags_subject_20': '',
    'documents_0_tags_subject_21': '',
    'documents_0_tags_subject_22': '',
    'documents_0_tags_subject_23': '',
    'documents_0_tags_subject_24': '',
    'documents_0_tags_subject_25': '',
    'documents_0_tags_subject_26': '',
    'documents_0_tags_geobuildings_2': '',
    'documents_0_tags_organisation_3': '',
    'documents_0_tags_organisation_4': '',
    'documents_0_tags_organisation_5': '',
    'documents_0_metadata_technique_2': '',
    'documents_0_tags_geographics_3': '',
    'documents_0_tags_geographics_4': '',
    'documents_0_tags_geographics_5': '',
    'documents_0_tags_awards_1': '',
    'documents_0_tags_person_2': '',
    'documents_0_metadata_subject_terms_4': '',
    'documents_0_tags_singheritage_4': '',
    'documents_0_tags_story_category_0': '',
    'documents_0_tags_geobuildings_3': '',
    'documents_0_metadata_inscription_language': '',
    'documents_0_tags_material_5': '',
    'documents_0_tags_organisation_6': '',
    'documents': '',
    'documents_0_tags_subject_27': '',
    'documents_0_tags_shape_2': '',
    'documents_0_tags_color_4': '',
    'documents_0_tags_city_3': '',
    'documents_0_tags_city_4': '',
    'documents_0_tags_objecttype_4': '',
    'documents_0_tags_place_category_0': '',
    'documents_0_tags_technique_3': '',
    'documents_0_tags_technique_4': '',
    'documents_0_tags_objecttype_5': '',
    'documents_0_tags_geographics_6': '',
    'documents_0_tags_city_5': '',
    'documents_0_tags_city_6': '',
    'documents_0_metadata_year_period_1': '',
    'documents_0_tags_person_3': '',
    'documents_0_tags_person_4': '',
    'documents_0_tags_person_5': '',
    'documents_0_tags_person_6': '',
    'documents_0_tags_person_7': '',
    'documents_0_tags_person_8': '',
    'documents_0_tags_person_9': '',
    'documents_0_tags_singheritage_5': '',
    'documents_0_tags_language_1': '',
    'documents_0_tags_shape_3': '',
    'documents_0_tags_shape_4': '',
    'documents_0_metadata_object_type_2': '',
    'documents_0_metadata_region_3': '',
    'documents_0_metadata_technique_3': '',
    'documents_0_tags_geobuildings_4': '',
    'documents_0_tags_technique_5': '',
    'documents_0_tags_technique_6': '',
    'documents_0_tags_technique_7': '',
    'documents_0_tags_technique_8': '',
    'documents_0_metadata_categories_2': '',
    'documents_0_tags_events_1': '',
    'documents_0_tags_programmes_0': '',
    'documents_0_tags_color_5': '',
    'documents_0_metadata_date_period_0': '',
    'documents_0_tags_subject_28': '',
    'documents_0_tags_subject_29': '',
    'documents_0_tags_subject_30': '',
    'documents_0_tags_subject_31': '',
    'documents_0_tags_subject_32': '',
    'documents_0_tags_subject_33': '',
    'documents_0_tags_geobuildings_5': '',
    'documents_0_tags_geobuildings_6': '',
    'documents_0_tags_geobuildings_7': '',
    'documents_0_metadata_scale_type': '',
    'documents_0_metadata_material_5': '',
}
'''
